[package]
name = "PathTrace"
version = "0.1.0"
edition = "2024"

[dependencies]
fastrand = "2.3.0"
rayon = "1.10.0"
bytemuck = { version = "1.16.1", features = ["derive"] }
pollster = "0.4.0"
wgpu = "0.19.4"
